### ISSUE TITLE
Many randon 500 errors

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/service-alti#65]
Unfortunately, I do not have the `POST`  data

```
[Sun Mar 29 07:58:41.657862 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922] mod_wsgi (pid=29203): Exception occurred processing WSGI script '/var/www/vhosts/service-alti/private/alti/apache/application.wsgi'.
[Sun Mar 29 07:58:41.659251 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922] Traceback (most recent call last):
[Sun Mar 29 07:58:41.659307 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
[Sun Mar 29 07:58:41.659423 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = self.execution_policy(environ, self)
[Sun Mar 29 07:58:41.659439 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
[Sun Mar 29 07:58:41.659458 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     return request.invoke_exception_view(reraise=True)
[Sun Mar 29 07:58:41.659468 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/view.py", line 768, in invoke_exception_view
[Sun Mar 29 07:58:41.659648 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     reraise_(*exc_info)
[Sun Mar 29 07:58:41.659664 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
[Sun Mar 29 07:58:41.659708 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     return router.invoke_request(request)
[Sun Mar 29 07:58:41.659735 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
[Sun Mar 29 07:58:41.659756 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = handle_request(request)
[Sun Mar 29 07:58:41.659799 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
[Sun Mar 29 07:58:41.659853 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = _error_handler(request, exc)
[Sun Mar 29 07:58:41.659865 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
[Sun Mar 29 07:58:41.659883 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     reraise(*exc_info)
[Sun Mar 29 07:58:41.659892 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
[Sun Mar 29 07:58:41.659906 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = handler(request)
[Sun Mar 29 07:58:41.659915 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
[Sun Mar 29 07:58:41.659930 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     registry, request, context, context_iface, view_name
[Sun Mar 29 07:58:41.659940 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/view.py", line 657, in _call_view
[Sun Mar 29 07:58:41.659954 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = view_callable(context, request)
[Sun Mar 29 07:58:41.659964 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 275, in wrapper
[Sun Mar 29 07:58:41.660085 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = view(context, request)
[Sun Mar 29 07:58:41.660105 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
[Sun Mar 29 07:58:41.660124 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     result = view(context, request)
[Sun Mar 29 07:58:41.660135 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
[Sun Mar 29 07:58:41.660149 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = getattr(inst, attr)()
[Sun Mar 29 07:58:41.660159 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/alti/views/profile.py", line 78, in json
[Sun Mar 29 07:58:41.660175 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     return self.__get_profile_from_helper(True)

[Sun Mar 29 07:58:41.659756 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = handle_request(request)
[Sun Mar 29 07:58:41.659799 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
[Sun Mar 29 07:58:41.659853 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = _error_handler(request, exc)
[Sun Mar 29 07:58:41.659865 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
[Sun Mar 29 07:58:41.659883 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     reraise(*exc_info)
[Sun Mar 29 07:58:41.659892 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
[Sun Mar 29 07:58:41.659906 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = handler(request)
[Sun Mar 29 07:58:41.659915 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
[Sun Mar 29 07:58:41.659930 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     registry, request, context, context_iface, view_name
[Sun Mar 29 07:58:41.659940 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/view.py", line 657, in _call_view
[Sun Mar 29 07:58:41.659954 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = view_callable(context, request)
[Sun Mar 29 07:58:41.659964 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 275, in wrapper
[Sun Mar 29 07:58:41.660085 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = view(context, request)
[Sun Mar 29 07:58:41.660105 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
[Sun Mar 29 07:58:41.660124 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     result = view(context, request)
[Sun Mar 29 07:58:41.660135 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/.venv/lib/python2.7/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
[Sun Mar 29 07:58:41.660149 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     response = getattr(inst, attr)()
[Sun Mar 29 07:58:41.660159 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/alti/views/profile.py", line 78, in json
[Sun Mar 29 07:58:41.660175 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     return self.__get_profile_from_helper(True)
[Sun Mar 29 07:58:41.660184 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/alti/views/profile.py", line 91, in __get_profile_from_helper
[Sun Mar 29 07:58:41.660198 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     output_to_json=output_to_json)
[Sun Mar 29 07:58:41.660207 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/alti/lib/profile_helpers.py", line 36, in get_profile
[Sun Mar 29 07:58:41.660286 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     coordinates=coordinates)
[Sun Mar 29 07:58:41.660299 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/alti/lib/profile_helpers.py", line 192, in _extract_z_values
[Sun Mar 29 07:58:41.660316 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     z = already_used_tile.get_height_for_coordinate(x, y)
[Sun Mar 29 07:58:41.660325 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]   File "/var/www/vhosts/service-alti/private/alti/alti/lib/raster/georaster.py", line 93, in get_height_for_coordinate
[Sun Mar 29 07:58:41.660385 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922]     self.file.seek(256 + (position_y + position_x * self.rows) * self.data_size)
[Sun Mar 29 07:58:41.660404 2020] [wsgi:error] [pid 29203] [remote 10.220.6.66:42922] ValueError: I/O operation on closed file


```

**Comment by loicgasser** [comment]
`ValueError: I/O operation on closed file` that's probably the issue. When you re-user older tiles that you red previously, for some reason the tile is closed.
Since https://github.com/geoadmin/service-alti/commit/b119f019d74dc14c0b9e7e4cc3c116b47c7dff44#diff-63cb2965e047a583c1bdeb4f3cc9b736
It seems that you are now keeping multiple files open at the same time. I think this is the problem.

**Comment by pakb** [comment]
yep, that might have been overkill, keeping the ref on them to look if next point is also in the last tile could be a good enough optimization. I'll revert back to close each tile after each use.
